### ISSUE TITLE
update EG25 via OpenWRT

### ISSUE THREAD

**Issue by dnwk** [Biktorgj/quectel_eg25_recovery#10]
I am wondering if I could run this update on an OpenWRT system that has EG25 attached via mini PCIe

**Comment by ASoTNetworks** [comment]
This is what I want to figure out too

**Comment by ASoTNetworks** [comment]
I figured it out you have to build https://github.com/Biktorgj/qfirehose in OpenWRT buildroot https://openwrt.org/docs/guide-developer/toolchain/crosscompile which will build qfirehose for your SoC. Then you can replace qfirehose with your own then run `./qfirehose -f ./` as in the readme file in this repo.

**Comment by Biktorgj** [comment]
I left statically linked binaries for both arm32 and arm64, if your board is arm based you can probably use that directly, otherwise yes, you'd have to build qfirehose yourself (or manually flash them with fastboot if openWRT has it)

**Comment by dnwk** [comment]
Thanks. Mine are MIPS. So do need to compile. I may try to connect my EG25 to a raspberry pi via USB and do it there.

**Comment by Biktorgj** [comment]
Closing it due to inactivity, if there's something else feel free to reopen the issue
