### ISSUE TITLE
Quirks Resolved

### ISSUE THREAD

**Issue by PsychoGame** [Biktorgj/quectel_eg25_recovery#11]
Hello @Biktorgj,

For those quirks I found the solution to this.
I was having a lot of issues as well on Manjaro ARM Phosh.
Stopping ModemManager through systemctl stops interference from ModemManager (Tries to re-initialize the modem again) and solves the Sahara flash failure:
`sudo systemctl stop ModemManager`
After successfully flashing the firmware you can restart ModemManager again.
If you could include this in the README, others might be helped out as well, as ModemManager in pmOS and Mobian will be updated eventually as well.

Greetings Jasper

**Comment by nexero** [comment]
Works for me in pmOS :+1: 
```sh
sudo rc-service modemmanager stop
sudo ./qfirehose -f ./
sudo rc-service modemmanager start
```

thanks for the hint @PsychoGame

**Comment by Biktorgj** [comment]
Thanks @PsychoGame!
Added the quirk to the readme: https://github.com/Biktorgj/quectel_eg25_recovery/commit/1351e026335d5b5fc395d232410388e082724d11
