### ISSUE TITLE
Add new version `EG25GGBR07A08M2G_30.004.30.004`

### ISSUE THREAD

**Issue by Zapeth** [Biktorgj/quectel_eg25_recovery#12]
I was curious if any newer firmware versions were available and indeed stumbled on a new version on quectel's forum, `EG25GGBR07A08M2G_30.004.30.004`  is available from posted sharepoint link at: https://forums.quectel.com/t/eg25-firmware-and-lwm2m/12126

Has anybody tested this yet with modem on Pinephone (including custom firmware)?

Looking at the firmware release changes it seems version `EG25GGBR07A08M2G_30.003.30.003` released before that, maybe this can also be found/requested somewhere.

**Comment by Biktorgj** [comment]
Hi and thanks for the link!
I haven't seen that firmware before, downloading it now...

Will give it a try and if there's nothing strange going on with it will upload it to the recovery repo (leaving this issue open until merged)

Edit: Firmware is build in september, it boots, and on first look, it seems to at least have more LTE profiles than previous versions:
+QMBNCFG: "List",0,1,1,"ROW_Generic_3GPP",0x0501081F,202108201
+QMBNCFG: "List",1,0,0,"VoLTE-ATT",0x0501033C,202105171
+QMBNCFG: "List",2,0,0,"hVoLTE-Verizon",0x05010141,202011021
+QMBNCFG: "List",3,0,0,"Sprint-VoLTE",0x05010205,202010201
+QMBNCFG: "List",4,0,0,"Commercial-TMO_VoLTE",0x05010505,202106241
+QMBNCFG: "List",5,0,0,"Telus-Commercial_DO",0x0580F601,202105061
+QMBNCFG: "List",6,0,0,"Commercial-SBM",0x05011C18,202004211
+QMBNCFG: "List",7,0,0,"Commercial-DT",0x05011F1C,202106171
+QMBNCFG: "List",8,0,0,"Reliance_OpnMkt",0x05011B38,202003251
+QMBNCFG: "List",9,0,0,"TF_Germany_VoLTE",0x05010C1B,202004151
+QMBNCFG: "List",11,0,0,"Volte_OpenMkt-Commercial-CMCC",0x05012071,202102221
+QMBNCFG: "List",12,0,0,"VoLTE_OPNMKT_CT",0x050113FC,202105131
+QMBNCFG: "List",13,0,0,"CU-VoLTE",0x05011508,202109101
+QMBNCFG: "List",14,0,0,"Telstra-Commercial_VoLTE",0x0580079E,202105192
+QMBNCFG: "List",15,0,0,"Commercial-KDDI",0x0501071D,202011192
+QMBNCFG: "List",16,0,0,"Commercial-DCM",0x05010D17,202104121
+QMBNCFG: "List",17,0,0,"Commercial-SKT",0x05012715,202103121
+QMBNCFG: "List",20,0,0,"Commercial-USCC",0x0504FC40,202011111
+QMBNCFG: "List",21,0,0,"Optus-Commercial_VoLTE",0x05800CA2,201910241
+QMBNCFG: "List",22,0,0,"STC_Saudi_VoLTE",0x0501FE01,201912231
+QMBNCFG: "List",23,0,0,"Commercial-Rogers",0x05018821,202108021

**Comment by Biktorgj** [comment]
Tested the full image a bit and booted and reported just fine
The ADSP firmware seems stable too (that one I've been using it for the last two days and so far no issues).
New firmware is here: https://github.com/Biktorgj/quectel_eg25_recovery/tree/EG25GGBR07A08M2G_30.004.30.004

Thank you @Zapeth!
