### ISSUE TITLE
firmware is the original

### ISSUE THREAD

**Issue by jackghg** [Biktorgj/quectel_eg25_recovery#3]
The firmware here is the original firmware or you tweaked it ?

**Comment by Biktorgj** [comment]
This repo only has "official" firmware packages (as official as they can be found on Quectel's forum or sharepoint). The only addition is the **qfirehose** blob to make it easier to change the firmware, but firmware files are untouched.

If looking for tweaks or mods, you can use the SDK repo: https://github.com/Biktorgj/pinephone_modem_sdk

**Comment by jackghg** [comment]
Oh ok, is this written somewhere ? Thanks for your good work anyway!
